config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  resources :users, :only => [:new, :create]
  resources :restaurants

  get '/display' => 'restaurants#display'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/my_page' => 'users#my_page'
  
  post '/generate_code', to: 'coupon_codes#generate_code', as: 'generate_code'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :restaurants
end

app/models/city.rb
class City < ApplicationRecord
    has_many :restaurants
end

app/models/coupon_code.rb
class CouponCode < ApplicationRecord
    validates_uniqueness_of :code
    validates_presence_of :code, :expires_at, :status
  
    def self.able_to_generate(user)
      most_recent_code = CouponCode.where(user: user).order(created_at: :desc).first
  
      if most_recent_code.nil?
        return true
      else
        time_since_last_code = Time.now - most_recent_code.created_at
        return time_since_last_code > 7.days
      end
    end
  end
  

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end

app/controllers/coupon_codes_controller.rb
class CouponCodesController < ApplicationController
    def generate_code
      coupon_code = CouponCode.new
      coupon_code.code = generate_unique_code
      coupon_code.expires_at = Time.now + 1.week
      coupon_code.status = "active"

      if coupon_code.save
        @code = coupon_code.code
        render 'users/my_page'
      else
        render json: { error: coupon_code.errors.full_messages }, status: :unprocessable_entity
      end
    end

    
    private

    def generate_unique_code
      code = SecureRandom.alphanumeric(10).upcase
      while CouponCode.find_by(code: code)
        code = SecureRandom.alphanumeric(10).upcase
      end
      code
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @cities = City.all 
        @categories = Category.all
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Category.find(params[:category]).restaurants.where(:city_id => params[:city]) 
    end

    def new
        @restaurant = Restaurant.new
    end

    def edit
        @restaurant = Restaurant.find params[:id]
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        if @restaurant.update(restaurant_params)
            @restaurant.categories = Category.where(id: params[:restaurant][:category_ids])
            redirect_to @restaurant
        else
            render :edit
        end
    end
        
    def show
        @restaurant = Restaurant.find params[:id]

        # OpenWeather API
        client = OpenWeather::Client.new(api_key: "f17ad8ba4bb969b686a122cb8d7671c6")
        city = City.find(@restaurant.city_id)
        data = client.current_weather(city: city.name)
        @description = data["weather"][0]["description"]
        @temperature = data["main"]["temp"] - 273.15
       
        # Google Places API
        client = GooglePlaces::Client.new("AIzaSyBP-kmma36SMH5UuQGsT05SwMUGmMZSNFo")
        spots = client.spots_by_query(@restaurant.name)
        @rating = spots.first.rating

        # Restaurant Navigator
        @previous_restaurant = Restaurant.where(city_id: @restaurant.city_id).where("id < ?", @restaurant.id).last
        @next_restaurant = Restaurant.where(city_id: @restaurant.city_id).where("id > ?", @restaurant.id).first
        if @previous_restaurant.nil?
            @previous_restaurant = Restaurant.where(city_id: @restaurant.city_id).last
        end
        if @next_restaurant.nil?
            @next_restaurant = Restaurant.where(city_id: @restaurant.city_id).first
        end

        # Show Restaurant's Category
        @category_name = Category.joins(:restaurants).where('restaurants.id = ?', @restaurant.id).pluck(:name).first

    end

    def display
        @cities = City.all
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            @restaurant.categories = Category.where(id: params[:restaurant][:category_ids])
            redirect_to @restaurant
        else
            render :new
        end
    end

    def destroy
        restaurant = Restaurant.find params[:id]
        restaurant.destroy
        redirect_to display_path
    end

    private
    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :description, :website, :logo, :image, :category_ids, :city_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end

    def create
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:error] = "Invalid email or password"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

    def restaurants
        @restaurant = Restaurant.find(params[:id])
        @names = @restaurant.name
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_for_admin, :only => [:index]
    
    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end

    def my_page
        @code = params[:code]
    end
    
    def restaurants
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupon_codes_helper.rb
module CouponCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eatgo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="collapse navbar-collapse container-fluid" id="navbarNav">
        <ul class="navbar-nav mb-2 mb-lg-0 col-md-5">
          <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Restaurants', display_path, class: "nav-link" %>
          </li>
            <% if @current_user.present? %>
          <li class="nav-item">
          <%= link_to "My Page", my_page_path, class: "nav-link" %>
          </li>
            <% else %>
          <li class="nav-item">
          <%= link_to "Sign up", new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign in", login_path, class: "nav-link" %>
          </li>
            <% end %>
        </ul>
        <div class="navbar-nav mb-2 mb-lg-0 ">
          <% if @current_user.present? %>
          <li class="nav-item">
          <%= link_to "Sign out: #{ @current_user.email }", login_path, :method => 'delete', class: "nav-link" %>
          </li>
        </div>
          <% end %>
      </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="topmargin">
<p>Choose your city:</p>
<%= form_tag("/restaurants", :method => 'get') do %>
<div class="container text-center">
  <div class="citytag row justify-content-center">
    <% @cities.each do |city| %>
    <div
      class="optionset nametag col-md-3 shadow-none p-3 mb-5 bg-body-tertiary rounded"
    >
      <%= label_tag do %>
      <span
        ><%= image_tag city.image, class: "cover" %>
        <div>
          <%= radio_button_tag :city, city.id, false, :required => true %><%=
          city.name %>
        </div></span
      >
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<p>Choose the category:</p>
<div class="container text-center">
<div class="d-flex flex-wrap justify-content-center">
    <% @categories.each do |category| %> 
    <div
      class="optionset nametag categoryset shadow-none p-2 mb-3 bg-body-tertiary rounded"
    ><div class="col-md-1"></div>
    <%= label_tag do %>
      <%= radio_button_tag :category, category.id, false, :required => true
      %><%= category.name %>
    </div>
    <div class="col-md-1"></div>
    <% end %> <% end %>
    <div></div>
  </div>
</div>

<div class="container">
  <div class="col-md text-center">
    <%= submit_tag "Search", class: "btn addbutton searchbutton" %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
    <div class="col-md-3 edittag">
    <%= f.label :name, :required => true %>:
    <%= f.text_field :name, class: "form-control", :required => true, :autofocus => true %>
    </div>

    <div class="col-mb-3 edittag">
    <%= f.label :address %>:
    <%= f.text_field :address, class: "form-control", :required => true %>
    </div>
    
    <div class="col-md-3 edittag">
    <%= f.label :description %>:
    <%= f.text_area :description, class: "form-control", rows:5 %>
    </div>
    
    <div class="col-mb-3 edittag">
    <%= f.label :website %>:
    <%= f.url_field :website, class: "form-control" %>
    </div>
    
    <div class="col-mb-3 edittag">
    <%= f.label :logo %>:
    <%= f.url_field :logo, class: "form-control", :required => true %>
    </div>
    
    <div class="col-mb-3 edittag">
    <%= f.label :image %>:
    <%= f.url_field :image, class: "form-control", :required => true %>
    </div>
    
    <div class="col-mb-3 edittag">
    <%= f.label :city_id %>:
    <%= f.select :city_id, City.pluck(:name, :id), :required => true %>
    </div>
    
    <div class="col-mb-3 edittag">
    <%= f.label :category_id %>:
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
    </div>
    
    <div class="container edittag">
    <div class="col-md text-center">
    <%= f.submit %>
    </div>
    </div>
<% end %>

app/views/restaurants/display.html.erb
<% if @current_user.present? %> 
  <% if @current_user.admin? %>
    <div class="controls newres">
    <%= link_to 'Add restaurant', new_restaurant_path(@restaurant), class: "userbutton btn addbutton shadow p-3 mb-5 bg-body-tertiary rounded" %>
    </div>
  <% end %> 
<% end %> 

<% @cities.each do |city| %>
<div class="container text-center">
  <h2><strong><%= city.name %></strong></h2>
  <div class="row align-items-center">
    <% city.restaurants.each do |restaurant| %>
    <div class="col-md-2">
      <%= link_to restaurant, target: :_blank do %>
      <div class="logoset">
        <%= image_tag(restaurant.logo, class: "logo") %>
        <div><%= restaurant.name %></div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="col-md text-center">
    <h1>Edit restaurant</h1>
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container text-center">
  <div class="row align-items-center">
    <% @restaurants.each do |restaurant| %>
    <div class="col-md-4 indextag">
      <%= link_to restaurant do %>
      <div class="logoset">
        <%= image_tag(restaurant.logo, class: "logo") %>
        <div><%= restaurant.name %></div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="col-md text-center">
    <h1>New restaurant</h1>
  </div>
</div>

<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<div class="container restaurantset text-center">
  <div class="row align-items-center">
    <div class="col-md-1"></div>
    <div class="col-md-5">
      <%= image_tag @restaurant.image, class: "img-fluid imageset" %>
    </div>

    <ul class="col-md-5 selectionbutton">
      <p class="keyname"><%= @restaurant.name %></p>
      <p class="description showfont information"><%= @restaurant.description %></p>
      <p class="showfont information"><strong>Category</strong>: <%= @category_name %> cuisines</p>
      <p class="showfont information"><strong>Google Reivew rating</strong>: <%= @rating %></p>
      <p class="showfont information">
        <strong>Current local weather</strong>: <%= @description %>, <%=
        @temperature.to_i %>°C
      </p>
      <p class="showfont information"><strong>Address</strong>: <%= @restaurant.address %></p>
      <p class="showfont information">
        <strong>Website</strong>: <%= link_to @restaurant.website,
        @restaurant.website, target: :_blank %>
      </p>
    </ul>
    <div class="col-md-1"></div>
  </div>
</div>

<div class="container selectionbutton">
  <div class="col-md text-center">
    <div class="controls">
      <% if @previous_restaurant.present? %> <%= link_to "<",
      restaurant_path(@previous_restaurant), class: "btn addbutton
      shadow p-3 mb-5 bg-body-tertiary rounded" %> <% end %> <% if
      @next_restaurant.present? %> <%= link_to ">",
      restaurant_path(@next_restaurant), class: "btn addbutton shadow
      p-3 mb-5 bg-body-tertiary rounded" %> <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="col-md text-center">
    <% if @current_user.present? %> <% if @current_user.admin? %>
    <div class="controls">
      <%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant), class:
      "addbutton btn shadow p-3 mb-5 bg-body-tertiary rounded" %> <%=
      link_to 'Delete restaurant', @restaurant, class: "btn addbutton
      shadow p-3 mb-5 bg-body-tertiary rounded", :method => 'delete', :data =>
      {:confirm => 'Are you sure?'} %>
    </div>
    <% end %> <% end %>
  </div>
</div>

app/views/session/new.html.erb
<div class="container">
  <div class="col-md text-center">
    <h2>Sign in</h2>
    <p><%= flash[:error] %></p>
    <%= form_tag login_path do %>
    <div class="mb-3">
      <%= label_tag :email %>: <%= email_field_tag :email, nil, :autofocus =>
      true %>
    </div>
    <div class="mb-3">
      <%= label_tag :password %>: <%= password_field_tag :password %>
    </div>
    <%= submit_tag "Sign in", class: "btn btn-primary addbutton" %> <% end %>
  </div>
</div>

app/views/users/my_page.html.erb
<div class="container">
  <div class="col-md text-center">
    <h2>Welcome!</h2>
    <%= link_to "Coupon Code", generate_code_path, method: :post, class: "btn
    btn-primary addbutton couponbutton" %>
  </div>
</div>
<% if @code %>
<p>Your coupon code is: <%= @code %></p>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="col-md text-center">
    <h2>Sign up</h2>
    <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ol>
    <% end %> <%= form_for @user do |f| %>
    <div class="formset">
      <div class="form">
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>:
          <%= f.email_field :email, class: "form-text", :autofocus => true %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>:
          <%= f.password_field :password, class: "form-text" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>:
          <%= f.password_field :password_confirmation, class: "form-text" %>
        </div>
      </div>
    </div>
    <%= f.submit 'Sign up!', class: "btn btn-primary addbutton" %> <% end %>
  </div>
</div>